fix(nix): update flake inputs (#1191)
fixes #1186 

- update flake inputs to pick up
https://github.com/pyproject-nix/pyproject.nix/commit/79f947627e7c356489ec602f3ce92e87a831f411
- revert manual and now unnecessary change to `uv.lock`
- address `selectors` import issue: `AttributeError: module 'selectors'
has no attribute 'SelectSelector' (consider renaming
'/home/dan/repos/github/xorq/python/xorq/selectors.py' since it has the
same name as the standard library module named 'selectors' and prevents
importing that standard library module)`